"""add recipe foundation tables

Revision ID: 85a0d7397576
Revises: c61ce24ab294
Create Date: 2026-08-24 14:18:58.646550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a0d7397576'
down_revision: Union[str, Sequence[str], None] = 'c61ce24ab294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cooking_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cuisine_type', sa.String(length=50), nullable=False),
    sa.Column('dish_category', sa.String(length=50), nullable=False),
    sa.Column('yield_type', sa.String(length=20), nullable=False),
    sa.Column('base_servings', sa.Integer(), nullable=True),
    sa.Column('fixed_yield_text', sa.String(length=100), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("\n            (\n                yield_type = 'servings'\n                AND base_servings IS NOT NULL\n                AND base_servings >= 1\n                AND fixed_yield_text IS NULL\n            )\n            OR\n            (\n                yield_type = 'fixed'\n                AND base_servings IS NULL\n                AND fixed_yield_text IS NOT NULL\n                AND length(trim(fixed_yield_text)) > 0\n            )\n            ", name='check_recipe_yield_values'),
    sa.CheckConstraint("yield_type IN ('servings', 'fixed')", name='check_recipe_yield_type'),
    sa.CheckConstraint('cooking_time_minutes >= 1', name='check_cooking_time_positive'),
    sa.CheckConstraint('length(trim(name)) > 0', name='check_recipe_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_name'), ['name'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_text', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('is_seasoning', sa.Boolean(), nullable=False),
    sa.Column('is_inventory_consumed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('\n            (\n                quantity IS NOT NULL\n                AND quantity > 0\n                AND quantity_text IS NULL\n            )\n            OR\n            (\n                quantity IS NULL\n                AND quantity_text IS NOT NULL\n                AND length(trim(quantity_text)) > 0\n            )\n            ', name='check_recipe_ingredient_quantity'),
    sa.CheckConstraint('\n            is_inventory_consumed = false\n            OR\n            (\n                is_seasoning = false\n                AND quantity IS NOT NULL\n                AND quantity_text IS NULL\n            )\n            ', name='check_inventory_consumption'),
    sa.CheckConstraint('\n            quantity IS NULL\n            OR\n            (\n                unit IS NOT NULL\n                AND length(trim(unit)) > 0\n            )\n            ', name='check_numeric_quantity_has_unit'),
    sa.CheckConstraint('display_order >= 1', name='check_ingredient_display_order'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'ingredient_id', name='uq_recipe_ingredient')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint('length(trim(description)) > 0', name='check_step_description_not_blank'),
    sa.CheckConstraint('step_number >= 1', name='check_step_number_positive'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'step_number', name='uq_recipe_step_number')
    )
    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_steps_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_steps_recipe_id'))

    op.drop_table('recipe_steps')
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_ingredient_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_name'))

    op.drop_table('recipes')
    # ### end Alembic commands ###
